Common Tenants Folder
redhat-ai-services/ai-accelerator pull request #69
Opened 2024-10-22 23:51 UTC by strangiato

@jland-redhat suggested the idea of creating a "common" overlay folder that can be included in the app-generator for the tenants when there is no difference between the different tenants.

This update adds his suggestion and cleans up many of the tenant folder overlays.

2024-10-23 00:04 UTC, strangiato commented
Example app successfully synced with `common` folder:

<img width="1099" alt="Screenshot 2024-10-22 at 6 03 10 PM" src="https://github.com/user-attachments/assets/8ad90816-6388-45f7-a625-cc6338662223">

2024-10-24 12:55 UTC, jland-redhat requested changes
Just one minor note

2024-10-24 12:55 UTC, jland-redhat commented on tenants/README.md
> +Alternatively, you can utilize the `common` overlay name to allow the same configuration to be applied to all clusters instead of creating an individual cluster folder in the overlays folder.
Can we add a quick note here that says 

"You can ONLY use one of or the other, i.e. you can't have like a rhoai-stable-2.10 and a common folder"

Just to make sure that is clear to folks

2024-10-24 17:06 UTC, jland-redhat approved these changes

2024-10-24 19:23 UTC, merged